@BooksAPI_HostAddress = https://localhost:7243

### GetAllUsers

GET {{BooksAPI_HostAddress}}/users/
Accept: application/json

### GetUserByName

GET {{BooksAPI_HostAddress}}/users/username/rachel/
Accept: application/json

### GetUserById

GET {{BooksAPI_HostAddress}}/users/id/1/
Accept: application/json

### GetAllBooks

GET {{BooksAPI_HostAddress}}/books/
Accept: application/json

### UpdateUserFavoriteBook
PATCH {{BooksAPI_HostAddress}}/users/fav/1/
Content-Type: application/json

{
    "favorite_book_id": 3
}

### AddUserToBookList
POST {{BooksAPI_HostAddress}}/user_books/
Content-Type: application/json

{
  "user_id": 1,
  "book_id": 3
}